<?php

namespace App\Modules\Frontend\Database\Seeders;

use App\Modules\Frontend\Models\FrontendSection;
use App\Modules\Frontend\Services\FrontendSectionService;
use Illuminate\Database\Seeder;

class FrontendSectionSeeder extends Seeder
{
    public static function definitions(): array
    {
        return [
            [
                'name' => 'Homepage Hero',
                'slug' => 'homepage-hero',
                'type' => 'home_hero',
                'status' => 'published',
                'description' => 'Primary hero section for the homepage.',
                'data' => [
                    'logos' => [
                        ['logo_media_id' => null, 'alt' => 'Vercel',       'fallback_src' => 'assets/logos/vercel.svg'],
                        ['logo_media_id' => null, 'alt' => 'Stripe',       'fallback_src' => 'assets/logos/stripe.svg'],
                        ['logo_media_id' => null, 'alt' => 'Figma',        'fallback_src' => 'assets/logos/figma.svg'],
                        ['logo_media_id' => null, 'alt' => 'Linear',       'fallback_src' => 'assets/logos/linear.svg'],
                        ['logo_media_id' => null, 'alt' => 'Notion',       'fallback_src' => 'assets/logos/notion.svg'],
                        ['logo_media_id' => null, 'alt' => 'Shopify',      'fallback_src' => 'assets/logos/shopify.svg'],
                        ['logo_media_id' => null, 'alt' => 'Cloudflare',   'fallback_src' => 'assets/logos/cloudflare.svg'],
                        ['logo_media_id' => null, 'alt' => 'Airbnb',       'fallback_src' => 'assets/logos/airbnb.svg'],
                        ['logo_media_id' => null, 'alt' => 'Spotify',      'fallback_src' => 'assets/logos/spotify.svg'],
                        ['logo_media_id' => null, 'alt' => 'Discord',      'fallback_src' => 'assets/logos/discord.svg'],
                        ['logo_media_id' => null, 'alt' => 'Google Cloud', 'fallback_src' => 'assets/logos/googlecloud.svg'],
                        ['logo_media_id' => null, 'alt' => 'Docker',       'fallback_src' => 'assets/logos/docker.svg'],
                        ['logo_media_id' => null, 'alt' => 'Kubernetes',   'fallback_src' => 'assets/logos/kubernetes.svg'],
                        ['logo_media_id' => null, 'alt' => 'TypeScript',   'fallback_src' => 'assets/logos/typescript.svg'],
                        ['logo_media_id' => null, 'alt' => 'Next.js',      'fallback_src' => 'assets/logos/nextdotjs.svg'],
                        ['logo_media_id' => null, 'alt' => 'React',        'fallback_src' => 'assets/logos/react.svg'],
                        ['logo_media_id' => null, 'alt' => 'Tailwind CSS', 'fallback_src' => 'assets/logos/tailwindcss.svg'],
                    ],
                ],
            ],
            [
                'name' => 'Homepage About',
                'slug' => 'homepage-about',
                'type' => 'home_about',
                'status' => 'published',
                'description' => 'About section for the homepage.',
                'data' => [
                    'eyebrow_text' => 'About our company',
                    'est_text' => 'EST · 2014 · SOFTIVUS',
                    'heading_line_one' => 'We build complete',
                    'heading_accent' => 'SaaS, web, and mobile',
                    'heading_line_two' => 'products — end to end.',
                    'intro_body' => 'Classic is a senior product team for founders and operators. From discovery to launch, we ship modern digital products with clean UI, scalable code, and a single delivery timeline.',
                    'video_label' => 'Showreel · 2 min',
                    'video_title' => 'How we ship products',
                    'video_year' => '2024',
                    'video_link' => 'https://www.youtube.com/watch?v=LXb3EKWsInQ',
                    'badge_number' => '10+',
                    'arch_caption_title' => 'A team that owns the outcome.',
                    'arch_caption_body' => 'Same senior engineers and designers from kickoff to launch — no junior handoffs.',
                    'body_paragraph_1' => 'We focus on smart, efficient, high-performance digital products. Strong expertise across product strategy, UI/UX, web and mobile engineering, and platform integrations — combined into one team that owns delivery from kickoff to ship.',
                    'body_paragraph_2' => 'Our work blends product strategy and engineering taste so the outcome looks the way it should and performs the way it must — for founders, operators, and growing companies.',
                    'differentiators_heading' => 'What makes us different',
                    'differentiators' => [
                        ['label' => 'Senior product team'],
                        ['label' => 'Engineering taste'],
                        ['label' => '120+ products shipped'],
                        ['label' => 'Remote-first, global'],
                    ],
                    'cta_text' => 'About Classic',
                    'cta_link' => '/about',
                ],
            ],
            [
                'name' => 'Homepage Services',
                'slug' => 'homepage-services',
                'type' => 'home_services',
                'status' => 'published',
                'description' => 'Services section for the homepage.',
                'data' => [],
            ],
            [
                'name' => 'Homepage Stats',
                'slug' => 'homepage-stats',
                'type' => 'home_stats_number',
                'status' => 'published',
                'description' => 'Stats section for the homepage.',
                'data' => [
                    'background_image_media_id' => null,
                    'card1_label' => 'Annual success rate',
                    'card1_target' => '98%',
                    'card1_badge' => '2x · YoY',
                    'card2_label' => 'Projects completed',
                    'card2_target' => '23K',
                    'card2_badge' => '1x+ · lifetime',
                ],
            ],
            [
                'name' => 'Homepage Solutions',
                'slug' => 'homepage-solutions',
                'type' => 'home_solutions',
                'status' => 'published',
                'description' => 'Solutions section for the homepage.',
                'data' => [
                    'eyebrow_text' => 'Solutions',
                    'heading_line_one' => 'One team,',
                    'heading_highlight' => 'six product shapes.',
                    'subheading' => 'Whatever the model — SaaS, marketplace, mobile, fintech — we ship the right architecture for the way it actually has to grow.',
                ],
            ],
            [
                'name' => 'Homepage Marquee',
                'slug' => 'homepage-marquee',
                'type' => 'home_marquee',
                'status' => 'published',
                'description' => 'Marquee section for the homepage.',
                'data' => [
                    'phrases' => [
                        ['text' => 'Build with intent'],
                        ['text' => 'Ship like a senior team'],
                        ['text' => 'Design that survives engineering'],
                        ['text' => 'Engineered for the way it grows'],
                        ['text' => 'From discovery to launch'],
                    ],
                    'badge_text' => 'SOFTIVUS · BUILD · SHIP · SOFTIVUS · BUILD · SHIP ·',
                ],
            ],
            [
                'name' => 'Homepage Why Us',
                'slug' => 'homepage-why-us',
                'type' => 'home_why_us',
                'status' => 'published',
                'description' => 'Why choose us section for the homepage.',
                'data' => [
                    'eyebrow_text' => 'Why Classic',
                    'heading_line_one' => 'Built like a senior product team.',
                    'heading_line_two' => 'Priced like an honest one.',
                    'subheading' => "What separates Classic is what we don't do — no junior handoffs, no locked code, no quarter-long timelines, no surprise invoices.",
                    'pillars' => [
                        [
                            'number' => '01',
                            'icon' => 'ph-users',
                            'color' => 'blue',
                            'size' => 'hero',
                            'title' => 'A senior team, not an agency funnel.',
                            'description' => 'Same senior engineers and designers from kickoff to launch.',
                            'stat_value' => '',
                            'stat_label' => '',
                            'checklist' => "No outsourcing layers\n9+ years average experience\nSame team start to finish\n4–6 specialists per build",
                        ],
                        [
                            'number' => '02',
                            'icon' => 'ph-lightning',
                            'color' => 'green',
                            'size' => 'std',
                            'title' => 'Eight weeks, not eight quarters.',
                            'description' => 'Discovery to launch on one timeline.',
                            'stat_value' => '8 wks',
                            'stat_label' => 'avg MVP timeline',
                            'checklist' => '',
                        ],
                        [
                            'number' => '03',
                            'icon' => 'ph-key',
                            'color' => 'navy',
                            'size' => 'std',
                            'title' => 'You own the code and the keys.',
                            'description' => 'Your GitHub, your cloud, your secrets.',
                            'stat_value' => 'Yours',
                            'stat_label' => 'repo + infra at handoff',
                            'checklist' => '',
                        ],
                        [
                            'number' => '04',
                            'icon' => 'ph-arrows-clockwise',
                            'color' => 'navy',
                            'size' => 'std',
                            'title' => 'Weekly demos, not quarterly reveals.',
                            'description' => 'Working software every week.',
                            'stat_value' => '7d',
                            'stat_label' => 'avg feedback loop',
                            'checklist' => '',
                        ],
                        [
                            'number' => '05',
                            'icon' => 'ph-activity',
                            'color' => 'blue',
                            'size' => 'std',
                            'title' => 'Observability built in, not bolted on.',
                            'description' => 'Logs, traces, and analytics from day one.',
                            'stat_value' => 'Day 1',
                            'stat_label' => 'telemetry live',
                            'checklist' => '',
                        ],
                        [
                            'number' => '06',
                            'icon' => 'ph-receipt',
                            'color' => 'green',
                            'size' => 'std',
                            'title' => 'Honest pricing, no surprise invoices.',
                            'description' => 'Fixed-scope sprints with a clear rate card.',
                            'stat_value' => '24h',
                            'stat_label' => 'change-order quote',
                            'checklist' => '',
                        ],
                        [
                            'number' => '07',
                            'icon' => 'ph-handshake',
                            'color' => 'blue',
                            'size' => 'wide',
                            'title' => 'Built for the long arc, not just launch.',
                            'description' => 'Same team for v2 and the year-two roadmap.',
                            'stat_value' => '',
                            'stat_label' => '',
                            'checklist' => "Same team for v2 and beyond\nRetainer or pay-as-you-need\nQuarterly roadmap reviews\nDirect line to engineers",
                        ],
                    ],
                    'footer_text' => "Sound like the team you'd want to build with?",
                    'footer_email' => 'support.com',
                    'footer_email_label' => '24/7 Available',
                    'footer_cta_text' => 'Book a 30-min scope call',
                    'footer_cta_link' => '#contact',
                ],
            ],
            [
                'name' => 'Homepage How Work',
                'slug' => 'homepage-how-work',
                'type' => 'home_how_work',
                'status' => 'published',
                'description' => 'Process section for the homepage.',
                'data' => [
                    'eyebrow_text' => 'How we work',
                    'heading_line_one' => 'Five phases.',
                    'heading_line_two' => 'One team. One timeline.',
                    'subheading' => 'From discovery to year-two roadmap — the same engineers and designers from kickoff to scale, with a clear deliverable at every step.',
                    'phases' => [
                        [
                            'number' => '01',
                            'duration' => '1 week',
                            'icon' => 'ph-compass',
                            'phase_label' => 'Discovery',
                            'title' => 'Understand the why before the what.',
                            'description' => 'Stakeholder interviews, technical audit, and a written scope doc. We leave with a one-page brief and a milestone plan you can sign off on.',
                            'deliverables' => "Discovery brief\nTechnical audit\nMilestone plan\nRisk register",
                        ],
                        [
                            'number' => '02',
                            'duration' => '2 weeks',
                            'icon' => 'ph-palette',
                            'phase_label' => 'Design',
                            'title' => 'Hi-fi designs ready to build, not pitch.',
                            'description' => 'Research-backed flows, design tokens, and motion specs in Figma. Every screen reviewed against the engineering plan so it survives the build.',
                            'deliverables' => "Hi-fi mockups\nDesign system tokens\nInteraction specs\nAccessibility audit",
                        ],
                        [
                            'number' => '03',
                            'duration' => '4–6 weeks',
                            'icon' => 'ph-code',
                            'phase_label' => 'Build',
                            'title' => 'Working software every week, not every quarter.',
                            'description' => 'Two-week sprints with a public preview environment. Telemetry from sprint one. Demo every Friday with a clear changelog.',
                            'deliverables' => "Preview environment\nWeekly demos\nTelemetry pipeline\nContinuous deploys",
                        ],
                        [
                            'number' => '04',
                            'duration' => '1 week',
                            'icon' => 'ph-rocket',
                            'phase_label' => 'Launch',
                            'title' => 'Production-ready, observable, and yours.',
                            'description' => 'Deploy to your cloud, your domain, your repo. Runbook, on-call rotation, and a post-launch report on day three.',
                            'deliverables' => "Production deploy\nRunbook + alerts\nDay-3 launch report\nCode handover",
                        ],
                        [
                            'number' => '05',
                            'duration' => 'Ongoing',
                            'icon' => 'ph-trend-up',
                            'phase_label' => 'Scale',
                            'title' => 'Same team, year-two roadmap.',
                            'description' => 'Quarterly roadmap reviews, retainer or pay-as-you-need engineering, and direct-line access to the team that shipped v1.',
                            'deliverables' => "Quarterly review\nRetainer engineering\nRoadmap planning\nOn-call support",
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Homepage Stack',
                'slug' => 'homepage-stack',
                'type' => 'home_stack',
                'status' => 'published',
                'description' => 'Technology stack section for the homepage.',
                'data' => [
                    'eyebrow_text' => 'Technology stack',
                    'heading_line_one' => 'The tools we ship with —',
                    'heading_highlight' => 'every one, opinionated.',
                    'subheading' => 'Every technology earns its place. No bloat, no trend-chasing — just the stack that ships fastest and scales longest.',
                ],
            ],
            [
                'name' => 'Homepage Testimonials',
                'slug' => 'homepage-testimonials',
                'type' => 'home_testimonials',
                'status' => 'published',
                'description' => 'Testimonials section for the homepage.',
                'data' => [
                    'eyebrow_text' => 'What teams say',
                    'heading_line_one' => 'Trusted by founders',
                    'heading_line_two' => 'who actually shipped.',
                    'subheading' => 'A decade of senior product engineering — measured in launches, retention, and the long arc of teams we still work with.',
                ],
            ],
            [
                'name' => 'Homepage Blog',
                'slug' => 'homepage-blog',
                'type' => 'home_blog',
                'status' => 'published',
                'description' => 'Homepage blog preview section.',
                'data' => [
                    'eyebrow_text' => 'From the Blog',
                    'heading_line_one' => 'Insights &',
                    'heading_highlight' => 'articles',
                    'subheading' => 'Practical WhatsApp automation, CRM, broadcast, and chatbot ideas for teams that want better customer conversations.',
                    'cta_text' => 'View all posts',
                    'cta_link' => '/blog',
                ],
            ],
            [
                'name' => 'Global FAQ',
                'slug' => 'global-faq',
                'type' => 'global_faq',
                'status' => 'published',
                'description' => 'Reusable FAQ section across the frontend.',
                'data' => [
                    'heading_line_one' => 'Common questions,',
                    'heading_line_two' => 'clear answers.',
                    'subheading' => 'The questions founders ask in the first 30-minute scope call.',
                    'call_card_title' => 'Talk to a senior engineer',
                    'call_card_body' => '30-minute scope call with someone who would actually build it. Usually within 48 hours.',
                    'call_card_cta_text' => 'Book a call',
                    'call_card_cta_link' => '#book-call',
                    'call_card_engineers_text' => '8 senior engineers · all on call',
                    'email_card_title' => 'Drop us a brief',
                    'email_card_body' => "Send a one-pager and we'll come back with a written response within two working days.",
                    'email_card_email' => 'hello.com',
                ],
            ],
            [
                'name' => 'Blog Hero',
                'slug' => 'blog-hero',
                'type' => 'blog_hero',
                'status' => 'published',
                'description' => 'Hero section for the blog page.',
                'data' => [
                    'eyebrow_text' => 'WaPro Blog',
                    'heading' => 'WhatsApp marketing insights for growing teams',
                    'subheading' => 'Guides on automation, broadcasts, chatbots, CRM workflows, and customer messaging that feels personal at scale.',
                ],
            ],
            [
                'name' => 'Blog Featured',
                'slug' => 'blog-featured',
                'type' => 'blog_featured',
                'status' => 'published',
                'description' => 'Featured articles section for the blog page.',
                'data' => [
                    'eyebrow_text' => 'Featured',
                    'heading' => 'Start with the latest playbook',
                ],
            ],
            [
                'name' => 'Blog Archive',
                'slug' => 'blog-archive',
                'type' => 'blog_archive',
                'status' => 'published',
                'description' => 'All articles grid section for the blog page.',
                'data' => [
                    'eyebrow_text' => 'Archive',
                    'heading' => 'All articles',
                    'subheading' => 'Browse practical guides for WhatsApp marketing, support automation, campaign operations, and customer growth.',
                ],
            ],
            [
                'name' => 'Blog Newsletter',
                'slug' => 'blog-newsletter',
                'type' => 'blog_newsletter',
                'status' => 'published',
                'description' => 'Newsletter signup section for the blog page.',
                'data' => [
                    'eyebrow_text' => 'Newsletter',
                    'heading' => 'Get WhatsApp growth notes in your inbox',
                    'subheading' => 'Practical automation, CRM, and campaign ideas for teams that use messaging every day.',
                    'button_text' => 'Subscribe',
                ],
            ],
            [
                'name' => 'FAQ Hero',
                'slug' => 'faq-hero',
                'type' => 'faq_hero',
                'status' => 'published',
                'description' => 'Hero section for the FAQ page.',
                'data' => [
                    'eyebrow' => 'FAQ',
                    'heading_line' => 'Questions teams ask',
                    'heading_highlight' => 'before they hire us.',
                    'description' => 'Clear answers about process, pricing, collaboration, ownership, and support.',
                ],
            ],
            [
                'name' => 'Service Category Hero',
                'slug' => 'service-category-hero',
                'type' => 'service_category_hero',
                'status' => 'published',
                'description' => 'Hero section for service category detail pages.',
                'data' => [],
            ],
            [
                'name' => 'Service Category Services',
                'slug' => 'service-category-services',
                'type' => 'service_category_services',
                'status' => 'published',
                'description' => 'Services grid for service category detail pages.',
                'data' => [],
            ],
            [
                'name' => 'Service Category Why Us',
                'slug' => 'service-category-why-us',
                'type' => 'service_category_why_us',
                'status' => 'published',
                'description' => 'Why choose us section for service category detail pages.',
                'data' => [],
            ],
            [
                'name' => 'Service Category Process',
                'slug' => 'service-category-process',
                'type' => 'service_category_process',
                'status' => 'published',
                'description' => 'Process steps section for service category detail pages.',
                'data' => [],
            ],
            [
                'name' => 'Project Category Hero',
                'slug' => 'project-category-hero',
                'type' => 'project_category_hero',
                'status' => 'published',
                'description' => 'Hero section for project category detail pages.',
                'data' => [],
            ],
            [
                'name' => 'Project Category Projects',
                'slug' => 'project-category-projects',
                'type' => 'project_category_projects',
                'status' => 'published',
                'description' => 'Project showcase section for project category detail pages.',
                'data' => [],
            ],
            [
                'name' => 'Project Category Stack',
                'slug' => 'project-category-stack',
                'type' => 'project_category_stack',
                'status' => 'published',
                'description' => 'Stack section for project category detail pages.',
                'data' => [],
            ],
            [
                'name' => 'Project Category Process',
                'slug' => 'project-category-process',
                'type' => 'project_category_process',
                'status' => 'published',
                'description' => 'Process section for project category detail pages.',
                'data' => [],
            ],
            [
                'name' => 'Global Contact',
                'slug' => 'global-contact',
                'type' => 'global_contact',
                'status' => 'published',
                'description' => 'Shared contact section usable on any page across the frontend.',
                'data' => [],
            ],
            [
                'name' => 'Team Hero',
                'slug' => 'team-hero',
                'type' => 'team_hero',
                'status' => 'published',
                'description' => 'Hero section for the team page.',
                'data' => [],
            ],
            [
                'name' => 'Team Members',
                'slug' => 'team-members',
                'type' => 'team_members',
                'status' => 'published',
                'description' => 'Grid showing team members.',
                'data' => [],
            ],
            [
                'name' => 'Team Culture',
                'slug' => 'team-culture',
                'type' => 'team_culture',
                'status' => 'published',
                'description' => 'Culture and values section for the team page.',
                'data' => [
                    'items' => [
                        ['icon' => 'ph-lightning',    'color' => '#2148ff', 'title' => 'Ship Fast',      'description' => 'We value working software over perfect plans. Iterate, learn, repeat.'],
                        ['icon' => 'ph-shield-check', 'color' => '#00c875', 'title' => 'Deep Ownership', 'description' => 'Everyone owns their work end-to-end — no hand-offs, no silos.'],
                        ['icon' => 'ph-chat',         'color' => '#8b42f5', 'title' => 'Radical Candor', 'description' => 'Honest feedback delivered with care. We grow through real conversations.'],
                        ['icon' => 'ph-globe',        'color' => '#ea6c28', 'title' => 'Remote-First',   'description' => 'Work from anywhere. We built the processes to make async the default.'],
                    ],
                ],
            ],
            [
                'name' => 'Team Presence',
                'slug' => 'team-presence',
                'type' => 'team_presence',
                'status' => 'published',
                'description' => 'Global presence stats section for the team page.',
                'data' => [
                    'items' => [
                        ['icon' => 'ph-users',     'color' => '#2148ff', 'value' => '42',   'label' => 'Team members'],
                        ['icon' => 'ph-globe',     'color' => '#00c875', 'value' => '8',    'label' => 'Countries'],
                        ['icon' => 'ph-star',      'color' => '#8b42f5', 'value' => '4.9★', 'label' => 'Client rating'],
                        ['icon' => 'ph-briefcase', 'color' => '#ea6c28', 'value' => '120+', 'label' => 'Products shipped'],
                    ],
                ],
            ],
            [
                'name' => 'Team Roles',
                'slug' => 'team-roles',
                'type' => 'team_roles',
                'status' => 'published',
                'description' => 'Open positions section for the team page.',
                'data' => [],
            ],
            [
                'name' => 'Careers Hero',
                'slug' => 'careers-hero',
                'type' => 'careers_hero',
                'status' => 'published',
                'description' => 'Hero section for the careers page.',
                'data' => [],
            ],
            [
                'name' => 'Careers Life',
                'slug' => 'careers-life',
                'type' => 'careers_life',
                'status' => 'published',
                'description' => 'Life at Classic section for the careers page.',
                'data' => [
                    'items' => [
                        ['icon' => 'ph-lightning',  'title' => 'Ships fast',      'description' => 'We move in weeks, not quarters. No endless planning cycles.'],
                        ['icon' => 'ph-chat-slash', 'title' => 'Async by default', 'description' => 'No pointless standups. Decisions happen in writing, not meetings.'],
                        ['icon' => 'ph-shield-slash', 'title' => 'No politics',      'description' => 'Flat structure, direct feedback, and zero org-chart theatre.'],
                        ['icon' => 'ph-users',       'title' => 'Real teamwork',    'description' => 'Designers, engineers, and PMs work together from day one.'],
                    ],
                ],
            ],
            [
                'name' => 'Careers Perks',
                'slug' => 'careers-perks',
                'type' => 'careers_perks',
                'status' => 'published',
                'description' => 'Benefits and perks section for the careers page.',
                'data' => [
                    'items' => [
                        ['icon' => 'ph-monitor',   'color' => 'blue',  'title' => 'Remote-first forever', 'description' => 'Work from anywhere. Async-friendly culture with no mandatory standups and no time-zone penalties.'],
                        ['icon' => 'ph-trend-up', 'color' => 'green', 'title' => 'Real ownership',       'description' => 'You lead features end-to-end. No ticket monkeys — every person here shapes how the product gets built.'],
                        ['icon' => 'ph-book-open', 'color' => 'navy', 'title' => 'Learning budget',      'description' => '$1,200/year for courses, books, and conferences. We pay for you to get better at your craft.'],
                        ['icon' => 'ph-clock',    'color' => 'blue',  'title' => 'Flexible hours',       'description' => 'We care about output, not clock time. Build your schedule around your life, not the other way around.'],
                        ['icon' => 'ph-laptop',   'color' => 'green', 'title' => 'Equipment stipend',    'description' => '$2,000 setup budget on day one. Get the gear you need to do your best work.'],
                        ['icon' => 'ph-airplane', 'color' => 'navy',  'title' => 'Annual offsite',       'description' => 'Once a year the whole team meets in person. Past locations: Lisbon, Tbilisi, Medellín.'],
                    ],
                ],
            ],
            [
                'name' => 'Careers Process',
                'slug' => 'careers-process',
                'type' => 'careers_process',
                'status' => 'published',
                'description' => 'Hiring process section for the careers page.',
                'data' => [
                    'steps' => [
                        ['number' => '01', 'title' => 'Submit Your Application',    'description' => "Share your resume and tell us why you'd be a great fit. We read every single one."],
                        ['number' => '02', 'title' => 'Initial Screening Call',     'description' => 'A quick 30-min chat to understand your background, goals, and role alignment — no prep needed.'],
                        ['number' => '03', 'title' => 'Technical / Skill Interview', 'description' => 'Showcase your craft. Any take-home work we ask for is compensated — your time is valuable.'],
                        ['number' => '04', 'title' => 'Culture Fit & Offer',        'description' => 'We align on values, expectations, and compensation — then move fast. No ghosting, ever.'],
                    ],
                ],
            ],
            [
                'name' => 'Careers Roles',
                'slug' => 'careers-roles',
                'type' => 'careers_roles',
                'status' => 'published',
                'description' => 'Open positions listing section for the careers page.',
                'data' => [],
            ],
            [
                'name' => 'About Hero',
                'slug' => 'about-hero',
                'type' => 'about_hero',
                'status' => 'published',
                'description' => 'Hero section for the about us page.',
                'data' => [],
            ],
            [
                'name' => 'About Story',
                'slug' => 'about-story',
                'type' => 'about_story',
                'status' => 'published',
                'description' => 'Story section for the about us page.',
                'data' => [
                    'eyebrow' => 'Who we are',
                    'heading' => 'A studio obsessed with craft and clarity',
                    'body_paragraph_one' => 'Classic started as a two-person consultancy with one conviction: most software fails because teams rush to code before they understand the problem. We took the opposite bet — start slow, think hard, then build fast.',
                    'body_paragraph_two' => "Today we're a 28-person studio spanning product design, full-stack engineering, and DevOps. We've shipped 60+ products across fintech, health-tech, logistics, and SaaS — always as embedded partners, never as body-shop contractors.",
                    'tags' => [
                        ['text' => 'Remote-first since day one'],
                        ['text' => 'No offshore hand-offs'],
                        ['text' => 'Fixed-scope, fixed-price'],
                    ],
                    'metrics' => [
                        ['icon' => 'ph-calendar', 'value' => '2018',  'label' => 'Founded — fully bootstrapped', 'color' => 'blue'],
                        ['icon' => 'ph-check',    'value' => '60+',   'label' => 'Products shipped',             'color' => 'blue'],
                        ['icon' => 'ph-users',    'value' => '28',    'label' => 'People on the team',           'color' => 'blue'],
                        ['icon' => 'ph-percent',  'value' => '98%',   'label' => 'Client retention rate',        'color' => 'navy'],
                        ['icon' => 'ph-star',     'value' => '4.9/5', 'label' => 'Average client rating',        'color' => 'brand'],
                    ],
                ],
            ],
            [
                'name' => 'About Values',
                'slug' => 'about-values',
                'type' => 'about_values',
                'status' => 'published',
                'description' => 'Values section for the about us page.',
                'data' => [
                    'eyebrow' => 'What drives us',
                    'heading_line_one' => 'Values that shape',
                    'heading_highlight' => 'every decision.',
                    'subheading' => "We don't hang our values on a wall — we bake them into how we scope, build, and ship.",
                    'items' => [
                        ['icon' => 'ph-eye',          'color' => 'blue',  'title' => 'Radical clarity',       'description' => 'No jargon, no hand-waving. We write specs in plain language, explain trade-offs in plain English, and never hide behind complexity.'],
                        ['icon' => 'ph-lightning',   'color' => 'green', 'title' => 'Speed with substance',   'description' => 'We move fast without cutting corners. Every sprint ends with shippable, tested code — not a pile of tech debt to clean up later.'],
                        ['icon' => 'ph-shield-check', 'color' => 'navy', 'title' => 'Full ownership',         'description' => "We act like founders, not vendors. That means flagging risk early, saying no when something won't work, and treating your roadmap like our own."],
                        ['icon' => 'ph-chat-circle', 'color' => 'blue',  'title' => 'Open by default',        'description' => 'Weekly demos, async Slack updates, and a Notion board you can always read. You never have to chase us for status.'],
                        ['icon' => 'ph-sparkle',     'color' => 'green', 'title' => 'Uncompromised quality',  'description' => 'We QA everything. Every screen, every edge case, every integration. If it ships with our name on it, it works.'],
                        ['icon' => 'ph-handshake',   'color' => 'navy',  'title' => 'Long-term thinking',     'description' => "We're not optimizing for the invoice — we're optimizing for your next funding round, your next million users, your next decade."],
                    ],
                ],
            ],
            [
                'name' => 'About Team',
                'slug' => 'about-team',
                'type' => 'about_team',
                'status' => 'published',
                'description' => 'Team section for the about us page.',
                'data' => [],
            ],
            [
                'name' => 'Support Hero',
                'slug' => 'support-hero',
                'type' => 'support_hero',
                'status' => 'published',
                'description' => 'Hero section for the support page.',
                'data' => [
                    'eyebrow' => 'Support',
                    'badge_label' => 'Classic Help Center',
                    'heading' => 'Welcome to Classic Support.',
                    'description' => 'We put special emphasis on customer support. Our dedicated support team is waiting to assist you. We always try to give you a better support experience.',
                    'hours_days' => 'Saturday to Thursday',
                    'hours_time' => '5:00AM – 2:00PM (GMT)',
                    'hours_holiday' => 'Friday is our weekly holiday!',
                    'access_note' => 'To keep our support system efficient and seamless and to keep your data safe and secure, we only keep this page accessible for registered users.',
                    'login_cta_text' => 'Login',
                    'register_cta_text' => 'Register',
                ],
            ],
            [
                'name' => 'Support Channels',
                'slug' => 'support-channels',
                'type' => 'support_channels',
                'status' => 'published',
                'description' => 'Contact channel cards for the support page.',
                'data' => [
                    'eyebrow' => 'How to Reach Us',
                    'heading' => 'Multiple Ways to Get Help',
                    'description' => 'Choose the channel that works best for you. Our team is trained to resolve issues quickly and keep you informed every step of the way.',
                    'channels' => [
                        [
                            'icon' => 'message-circle',
                            'color' => 'blue',
                            'title' => 'Live Chat',
                            'description' => 'Chat with our support agents in real time. Fastest response for urgent issues and quick questions.',
                            'features' => "Avg. response under 5 minutes\nScreen sharing available\nFile attachment supported",
                            'cta_text' => 'Start a Chat',
                            'cta_link' => '#',
                        ],
                        [
                            'icon' => 'mail',
                            'color' => 'green',
                            'title' => 'Submit a Ticket',
                            'description' => "Open a formal support ticket for detailed issues. We track every ticket until it's fully resolved.",
                            'features' => "Reply within 24 hours\nFull issue tracking & history\nPriority escalation available",
                            'cta_text' => 'Open Ticket',
                            'cta_link' => '#',
                        ],
                        [
                            'icon' => 'book-open',
                            'color' => 'navy',
                            'title' => 'Knowledge Base',
                            'description' => 'Browse our comprehensive documentation. Find step-by-step guides, tutorials, and answers 24/7.',
                            'features' => "200+ articles & tutorials\nVideo walkthroughs included\nUpdated weekly",
                            'cta_text' => 'Browse Docs',
                            'cta_link' => '#',
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Support Why',
                'slug' => 'support-why',
                'type' => 'support_why',
                'status' => 'published',
                'description' => 'Why our support section for the support page.',
                'data' => [
                    'eyebrow' => 'Why Choose Us',
                    'heading' => 'Support You Can Actually Rely On',
                    'description' => "We don't just answer tickets — we solve problems. Our team is trained, empowered, and committed to your success.",
                    'stat_one_value' => '98%',
                    'stat_one_label' => 'Satisfaction rate',
                    'stat_two_value' => '< 5 min',
                    'stat_two_label' => 'Avg. first reply',
                    'rating' => '4.9',
                    'rating_label' => 'Average Support Rating',
                    'rating_count' => 'Based on 2,800+ reviews',
                    'tickets_resolved' => '10K+',
                    'happy_clients' => '23K+',
                    'feature_cards' => [
                        ['icon' => 'zap',          'color' => 'blue',  'title' => 'Fast First Response',       'description' => 'Live chat replies in under 5 minutes during business hours. Tickets acknowledged within 1 hour.',            'position' => 'left'],
                        ['icon' => 'shield-check', 'color' => 'green', 'title' => 'Secure & Private',          'description' => 'All support interactions are encrypted. Your project data is never shared or accessed without permission.',  'position' => 'left'],
                        ['icon' => 'users',        'color' => 'blue',  'title' => 'Dedicated Account Support', 'description' => 'Enterprise clients get a dedicated account manager who knows your project inside and out.',                  'position' => 'right'],
                        ['icon' => 'globe',        'color' => 'green', 'title' => 'Multi-Language Support',    'description' => 'Our team speaks English, Arabic, and Bengali — serving clients across Asia, the Middle East, and beyond.',  'position' => 'right'],
                    ],
                ],
            ],
            [
                'name' => 'Support CTA',
                'slug' => 'support-cta',
                'type' => 'support_cta',
                'status' => 'published',
                'description' => 'Dark CTA banner for the support page.',
                'data' => [
                    'badge_label' => 'Support Team Ready',
                    'heading' => "Still Have Questions? We're Here to Help.",
                    'description' => 'Log in to access the full support portal or create an account to get started in under a minute.',
                    'login_cta_text' => 'Login to Support Portal',
                    'register_cta_text' => 'Create Free Account',
                ],
            ],
            [
                'name' => 'Contact Page Hero',
                'slug' => 'contact-page-hero',
                'type' => 'contact_page_hero',
                'status' => 'published',
                'description' => 'Hero section for the contact page.',
                'data' => [
                    'eyebrow' => 'Get in touch',
                    'heading_line' => "Let's build something",
                    'heading_highlight' => 'great together.',
                    'description' => 'Whether you have a fully scoped project or just an early idea — reach out. We respond within 48 hours and our first call is always free.',
                    'trust_signals' => [
                        ['icon' => 'ph-clock',        'color' => 'green', 'label' => 'Reply in 48 hrs',  'detail' => '— guaranteed'],
                        ['icon' => 'ph-calendar',     'color' => 'blue',  'label' => 'Free scope call',  'detail' => '— 30 minutes, no pitch'],
                        ['icon' => 'ph-shield-check', 'color' => 'blue',  'label' => 'NDA available',    'detail' => '— on request'],
                    ],
                ],
            ],
            [
                'name' => 'Contact Page Form',
                'slug' => 'contact-page-form',
                'type' => 'contact_page_form',
                'status' => 'published',
                'description' => 'Contact information and enquiry form for the contact page.',
                'data' => [],
            ],
            [
                'name' => 'Contact Page Offices',
                'slug' => 'contact-page-offices',
                'type' => 'contact_page_offices',
                'status' => 'published',
                'description' => 'Office locations grid for the contact page.',
                'data' => [
                    'eyebrow' => 'Our offices',
                    'heading' => "We're distributed — but always nearby.",
                    'offices' => [
                        [
                            'name' => 'San Francisco, USA',
                            'address' => "340 Pine Street, Suite 800\nCA 94104",
                            'meta' => 'HQ · PST (UTC-8)',
                            'icon' => 'building-2',
                            'color' => 'blue',
                        ],
                        [
                            'name' => 'London, UK',
                            'address' => "12 Finsbury Square\nLondon EC2A 1AR",
                            'meta' => 'EU Hub · GMT (UTC+0)',
                            'icon' => 'building-2',
                            'color' => 'blue',
                        ],
                        [
                            'name' => 'Remote-first team',
                            'address' => 'Engineers & designers spread across 12 countries.',
                            'meta' => 'Always async-ready',
                            'icon' => 'globe',
                            'color' => 'green',
                        ],
                    ],
                ],
            ],
        ];
    }

    public function run(): void
    {
        /** @var FrontendSectionService $service */
        $service = app(FrontendSectionService::class);

        foreach (self::definitions() as $section) {
            FrontendSection::updateOrCreate(
                ['slug' => $section['slug']],
                [
                    'name' => $section['name'],
                    'type' => $section['type'],
                    'status' => $section['status'],
                    'description' => $section['description'],
                    'data' => $service->normalizeData($section['type'], $section['data']),
                    'theme_overrides' => [],
                    'preview_image_media_id' => null,
                ]
            );
        }
    }
}
