<?php

return [
    'providers' => [
        'whatsapp' => [
            'label' => 'WhatsApp',
            'title' => 'WhatsApp Business',
            'icon' => 'ph-whatsapp-logo',
            'description' => 'Connect a WhatsApp Business number for inbox, campaigns, templates, and automation.',
            'webhook_hint' => 'Use this provider webhook URL in Meta app webhook settings.',
            'webhook_required' => true,
            'connect_mode' => 'whatsapp',
            'identifier_label' => 'Phone Number ID',
            'display_label' => 'Display Phone',
            'capabilities' => ['Inbox', 'Campaigns', 'Templates', 'Webhooks'],
            'campaign' => true,
            'inbox' => true,
            'publishing' => false,
            'requires_provider_identity' => false,
            'connection_test_required' => true,
            'fields' => [],
        ],
        'telegram' => [
            'label' => 'Telegram',
            'title' => 'Telegram Bot',
            'icon' => 'ph-telegram-logo',
            'description' => 'Connect a Telegram bot for subscriber campaigns, channel broadcasts, inbound messages, and automation.',
            'webhook_hint' => 'Use this provider webhook URL as your Telegram bot webhook endpoint.',
            'webhook_required' => true,
            'connect_mode' => 'manual',
            'identifier_label' => 'Bot Username',
            'display_label' => 'Bot Name',
            'capabilities' => ['Campaigns', 'Inbox', 'Templates', 'Automation', 'Webhooks'],
            'campaign' => true,
            'inbox' => true,
            'publishing' => false,
            'requires_provider_identity' => true,
            'connection_test_required' => true,
            'fields' => [
                ['name' => 'name', 'label' => 'Channel Name', 'placeholder' => 'e.g. Support Bot', 'required' => true],
                ['name' => 'provider_account_id', 'label' => 'Bot Username or ID', 'placeholder' => 'e.g. wapro_support_bot', 'required' => true],
                ['name' => 'provider_display_id', 'label' => 'Display Name', 'placeholder' => 'e.g. WaPro Support Bot'],
                ['name' => 'access_token', 'label' => 'Bot Token', 'placeholder' => 'Stored encrypted and never displayed', 'type' => 'password'],
            ],
        ],
        'email' => [
            'label' => 'Email',
            'title' => 'Email Channel',
            'icon' => 'ph-envelope-simple',
            'description' => 'Connect an email delivery channel for campaigns using SMTP, Mailgun, or Sendmail.',
            'webhook_required' => false,
            'connect_mode' => 'manual',
            'identifier_label' => 'Channel Name',
            'display_label' => 'From Address',
            'capabilities' => ['Campaigns'],
            'campaign' => true,
            'inbox' => false,
            'publishing' => false,
            'requires_provider_identity' => false,
            'connection_test_required' => true,
            'credential_provider_field' => 'mail_mailer',
            'fields' => [
                ['name' => 'name', 'label' => 'Channel Name', 'placeholder' => 'e.g. Primary Email', 'required' => true],
                ['name' => 'provider_display_id', 'label' => 'From Address', 'placeholder' => 'e.g. noreply@example.com', 'required' => true],
                ['name' => 'mail_mailer', 'label' => 'Email Provider', 'type' => 'select', 'options' => ['smtp' => 'SMTP', 'mailgun' => 'Mailgun', 'sendmail' => 'Sendmail', 'log' => 'Log (Testing)'], 'required' => true],
                ['name' => 'mail_from_name', 'label' => 'From Name', 'placeholder' => 'e.g. WaPro'],
                ['name' => 'mail_host', 'label' => 'SMTP Host', 'placeholder' => 'e.g. smtp.mailgun.org', 'required' => true, 'show_when' => ['mail_mailer' => 'smtp']],
                ['name' => 'mail_port', 'label' => 'SMTP Port', 'type' => 'number', 'placeholder' => 'e.g. 587', 'required' => true, 'show_when' => ['mail_mailer' => 'smtp']],
                ['name' => 'mail_encryption', 'label' => 'Encryption', 'type' => 'select', 'options' => ['tls' => 'TLS', 'ssl' => 'SSL', 'none' => 'None'], 'default' => 'tls', 'required' => true, 'show_when' => ['mail_mailer' => 'smtp']],
                ['name' => 'mail_username', 'label' => 'SMTP Username', 'type' => 'text', 'show_when' => ['mail_mailer' => 'smtp']],
                ['name' => 'mail_password', 'label' => 'SMTP Password', 'type' => 'password', 'secret' => true, 'required' => true, 'show_when' => ['mail_mailer' => 'smtp']],
                ['name' => 'mailgun_domain', 'label' => 'Mailgun Domain', 'placeholder' => 'e.g. mg.example.com', 'required' => true, 'show_when' => ['mail_mailer' => 'mailgun']],
                ['name' => 'mailgun_secret', 'label' => 'Mailgun Secret', 'type' => 'password', 'secret' => true, 'required' => true, 'show_when' => ['mail_mailer' => 'mailgun']],
                ['name' => 'mailgun_endpoint', 'label' => 'Mailgun Endpoint', 'placeholder' => 'e.g. api.mailgun.net', 'default' => 'api.mailgun.net', 'show_when' => ['mail_mailer' => 'mailgun']],
            ],
        ],
        'sms' => [
            'label' => 'SMS',
            'title' => 'SMS Channel',
            'icon' => 'ph-chat-text',
            'description' => 'Connect an SMS gateway for campaigns using Twilio or Vonage.',
            'webhook_required' => false,
            'connect_mode' => 'manual',
            'identifier_label' => 'Channel Name',
            'display_label' => 'From Number',
            'capabilities' => ['Campaigns'],
            'campaign' => true,
            'inbox' => false,
            'publishing' => false,
            'requires_provider_identity' => false,
            'connection_test_required' => true,
            'credential_provider_field' => 'sms_provider',
            'fields' => [
                ['name' => 'name', 'label' => 'Channel Name', 'placeholder' => 'e.g. Primary SMS', 'required' => true],
                ['name' => 'provider_display_id', 'label' => 'From Number', 'placeholder' => 'e.g. +1234567890', 'required' => true],
                ['name' => 'sms_provider', 'label' => 'SMS Provider', 'type' => 'select', 'options' => ['vonage' => 'Vonage', 'twilio' => 'Twilio', 'log' => 'Log (Testing)'], 'required' => true],
                ['name' => 'twilio_sid', 'label' => 'Twilio Account SID', 'type' => 'text', 'required' => true, 'show_when' => ['sms_provider' => 'twilio']],
                ['name' => 'twilio_auth_token', 'label' => 'Twilio Auth Token', 'type' => 'password', 'secret' => true, 'required' => true, 'show_when' => ['sms_provider' => 'twilio']],
                ['name' => 'vonage_api_key', 'label' => 'Vonage API Key', 'type' => 'text', 'required' => true, 'show_when' => ['sms_provider' => 'vonage']],
                ['name' => 'vonage_api_secret', 'label' => 'Vonage API Secret', 'type' => 'password', 'secret' => true, 'required' => true, 'show_when' => ['sms_provider' => 'vonage']],
            ],
        ],
        'messenger' => [
            'label' => 'Messenger',
            'title' => 'Messenger Page',
            'icon' => 'ph-messenger-logo',
            'description' => 'Connect a Facebook Page for Messenger conversations and automation.',
            'webhook_hint' => 'Use this provider webhook URL for Messenger events.',
            'webhook_required' => true,
            'connect_mode' => 'manual',
            'identifier_label' => 'Page ID',
            'display_label' => 'Page Name',
            'capabilities' => ['Inbox', 'Automation', 'Webhooks'],
            'campaign' => false,
            'inbox' => true,
            'publishing' => false,
            'requires_provider_identity' => true,
            'connection_test_required' => true,
            'fields' => [
                ['name' => 'name', 'label' => 'Channel Name', 'placeholder' => 'e.g. Support Page', 'required' => true],
                ['name' => 'provider_account_id', 'label' => 'Facebook Page ID', 'placeholder' => 'e.g. 1122334455', 'required' => true],
                ['name' => 'provider_display_id', 'label' => 'Page Name', 'placeholder' => 'e.g. WaPro Support'],
                ['name' => 'access_token', 'label' => 'Page Access Token', 'placeholder' => 'Stored encrypted and never displayed', 'type' => 'password'],
            ],
        ],
        'instagram' => [
            'label' => 'Instagram',
            'title' => 'Instagram Business',
            'icon' => 'ph-instagram-logo',
            'description' => 'Connect an Instagram Business account for DMs, comments, mentions, and automation.',
            'webhook_hint' => 'Use this provider webhook URL for Instagram events.',
            'webhook_required' => true,
            'connect_mode' => 'manual',
            'identifier_label' => 'Instagram Account ID',
            'display_label' => 'Username',
            'capabilities' => ['Inbox', 'Comments', 'Automation', 'Webhooks'],
            'campaign' => false,
            'inbox' => true,
            'publishing' => false,
            'requires_provider_identity' => true,
            'connection_test_required' => true,
            'fields' => [
                ['name' => 'name', 'label' => 'Channel Name', 'placeholder' => 'e.g. Instagram Support', 'required' => true],
                ['name' => 'provider_account_id', 'label' => 'Instagram Account ID', 'placeholder' => 'e.g. 17841400000000000', 'required' => true],
                ['name' => 'provider_display_id', 'label' => 'Username', 'placeholder' => 'e.g. wapro.app'],
                ['name' => 'access_token', 'label' => 'Page Access Token', 'placeholder' => 'Stored encrypted and never displayed', 'type' => 'password'],
            ],
        ],
        'website_widget' => [
            'label' => 'Website widget',
            'title' => 'Website Chat Widget',
            'icon' => 'ph-browser',
            'description' => 'Inbox conversations created by public website chatbot widgets.',
            'webhook_required' => false,
            'connect_mode' => 'internal',
            'identifier_label' => 'Widget',
            'display_label' => 'Website visitor',
            'capabilities' => ['Inbox', 'Automation', 'Chatbot'],
            'campaign' => false,
            'inbox' => true,
            'publishing' => false,
            'requires_provider_identity' => false,
            'connection_test_required' => false,
            'fields' => [],
        ],
        'threads' => [
            'label' => 'Threads',
            'title' => 'Threads Account',
            'icon' => 'ph-threads-logo',
            'description' => 'Connect a Threads account for publishing and webhook events.',
            'webhook_hint' => 'Use this provider webhook URL when Threads webhooks are enabled.',
            'webhook_required' => true,
            'connect_mode' => 'manual',
            'identifier_label' => 'Threads Account ID',
            'display_label' => 'Handle',
            'capabilities' => ['Publishing', 'Inbox', 'Webhooks'],
            'campaign' => false,
            'inbox' => true,
            'publishing' => true,
            'requires_provider_identity' => false,
            'connection_test_required' => true,
            'fields' => [
                ['name' => 'name', 'label' => 'Channel Name', 'placeholder' => 'e.g. Brand Threads', 'required' => true],
                ['name' => 'provider_account_id', 'label' => 'Threads Account ID', 'placeholder' => 'e.g. 9876543210', 'required' => true],
                ['name' => 'provider_display_id', 'label' => 'Threads Handle', 'placeholder' => 'e.g. @wapro'],
                ['name' => 'access_token', 'label' => 'Access Token', 'placeholder' => 'Stored encrypted and never displayed', 'type' => 'password'],
            ],
        ],
    ],
];
