<x-layouts.user :title="__('WhatsApp store setup')">
    <div class="space-y-6">
        <header class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-sm font-semibold text-primary">{{ __('WhatsApp commerce') }}</p><h1 class="heading-3 text-title">{{ __('Store setup and catalog health') }}</h1><p class="mt-1 max-w-3xl text-sm text-body">{{ __('Connect an existing Meta catalog, choose scheduled feed or direct API synchronization, then verify every production requirement.') }}</p></div><x-ui.button variant="outline" href="{{ route('user.whatsapp-cloud.channel-setup') }}"><i class="ph ph-whatsapp-logo"></i> {{ __('Manage WhatsApp channel') }}</x-ui.button></header>

        @include('commerce::user.partials.help', ['helpKey' => 'catalog'])

        <section class="section-card">
            <div class="grid gap-4 lg:grid-cols-5">@foreach([__('Channel'), __('Catalog'), __('Sync mode'), __('Commerce'), __('Verify')] as $index => $label)<div class="rounded-xl bg-section p-3"><span class="grid h-7 w-7 place-items-center rounded-full bg-primary text-xs font-bold text-neutral-0">{{ $index + 1 }}</span><p class="mt-2 text-sm font-semibold text-title">{{ $label }}</p></div>@endforeach</div>
            <form method="POST" action="{{ route('user.commerce.catalog.store') }}" class="mt-6 grid gap-5 md:grid-cols-2">@csrf
                <div><label class="form-label" for="channel_account_id">{{ __('Connected WhatsApp channel') }}</label><select id="channel_account_id" class="form-input" name="channel_account_id" required><option value="">{{ __('Select channel') }}</option>@foreach($channels as $channel)<option value="{{ $channel->id }}">{{ $channel->name }} · {{ str($channel->status->value ?? $channel->status)->title() }}</option>@endforeach</select><p class="mt-1 text-xs text-body">{{ __('The encrypted channel token is reused; it is never displayed here.') }}</p></div>
                <div><label class="form-label" for="meta_catalog_id">{{ __('Existing Meta catalog ID') }}</label><input id="meta_catalog_id" class="form-input" name="meta_catalog_id" required maxlength="120" placeholder="123456789012345"><p class="mt-1 text-xs text-body">{{ __('Find this ID in Meta Commerce Manager.') }}</p></div>
                <fieldset class="md:col-span-2"><legend class="form-label">{{ __('Synchronization mode') }}</legend><div class="grid gap-3 md:grid-cols-2"><label class="flex cursor-pointer gap-3 rounded-2xl border border-border p-4"><input type="radio" name="sync_mode" value="feed" checked class="mt-1"><span><strong class="block text-title">{{ __('Scheduled feed') }}</strong><span class="text-sm text-body">{{ __('Most reliable setup. Meta periodically downloads your protected CSV URL.') }}</span></span></label><label class="flex cursor-pointer gap-3 rounded-2xl border border-border p-4"><input type="radio" name="sync_mode" value="api" class="mt-1"><span><strong class="block text-title">{{ __('Direct Meta API') }}</strong><span class="text-sm text-body">{{ __('Queued item synchronization after catalog access and token capability checks pass.') }}</span></span></label></div></fieldset>
                <input type="hidden" name="is_active" value="1"><div class="md:col-span-2"><x-forms.submit :label="__('Save catalog connection')" /></div>
            </form>
        </section>

        <div class="space-y-5">
            @forelse($catalogs as $catalog)
                @php($health = $diagnostics[$catalog->id])
                <article class="section-card">
                    <div class="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><div class="flex flex-wrap items-center gap-2"><h2 class="heading-5 text-title">{{ $catalog->channelAccount?->name }}</h2><span class="badge badge-soft">{{ strtoupper($catalog->sync_mode) }}</span><span class="badge {{ $health['ready'] ? 'bg-success/10 text-success' : 'bg-warning/10 text-warning' }}">{{ $health['ready'] ? __('Ready') : trans_choice(':count issue|:count issues', $health['blocking_count'], ['count' => $health['blocking_count']]) }}</span></div><p class="mt-1 text-sm text-body">{{ __('Meta catalog') }}: {{ $catalog->meta_catalog_id }}</p></div><div class="flex flex-wrap gap-2">@if($catalog->sync_mode === 'api')<form method="POST" action="{{ route('user.commerce.catalog.sync', $catalog) }}">@csrf<x-forms.submit :label="__('Sync now')" /></form>@endif<form method="POST" action="{{ route('user.commerce.catalog.token.rotate', $catalog) }}" x-on:submit="if (!confirm('{{ __('Rotate this feed token? Meta must be updated with the new URL.') }}')) $event.preventDefault()">@csrf<x-forms.submit variant="outline" :label="__('Rotate feed token')" /></form></div></div>

                    <div class="mt-5 grid gap-4 lg:grid-cols-[1.2fr_1fr]">
                        <div><h3 class="text-sm font-semibold text-title">{{ __('Readiness checks') }}</h3><div class="mt-3 grid gap-2 sm:grid-cols-2">@foreach($health['checks'] as $check)<div class="flex items-start gap-2 rounded-xl bg-section p-3"><i class="ph {{ $check['passed'] ? 'ph-check-circle text-success' : 'ph-warning-circle text-warning' }} mt-0.5"></i><div><p class="text-sm font-semibold text-title">{{ str($check['code'])->replace('_', ' ')->title() }}</p><p class="text-xs text-body">{{ $check['message'] }}</p></div></div>@endforeach</div></div>
                        <div><h3 class="text-sm font-semibold text-title">{{ __('Feed and synchronization') }}</h3><div class="mt-3 rounded-xl bg-section p-3"><p class="break-all font-mono text-xs text-body">{{ route('commerce.catalog.feed', $catalog->feed_token) }}</p></div><dl class="mt-3 grid grid-cols-2 gap-3 text-sm"><div class="rounded-xl bg-section p-3"><dt class="text-body">{{ __('Items') }}</dt><dd class="font-semibold text-title">{{ $catalog->last_item_count }}</dd></div><div class="rounded-xl bg-section p-3"><dt class="text-body">{{ __('Last success') }}</dt><dd class="font-semibold text-title">{{ $catalog->last_successful_at?->diffForHumans() ?? __('Never') }}</dd></div><div class="rounded-xl bg-section p-3"><dt class="text-body">{{ __('Sync status') }}</dt><dd class="font-semibold text-title">{{ str($catalog->last_sync_status ?? 'not run')->replace('_', ' ')->title() }}</dd></div><div class="rounded-xl bg-section p-3"><dt class="text-body">{{ __('Failed items') }}</dt><dd class="font-semibold text-title">{{ $catalog->itemSyncs->where('status', 'failed')->count() }}</dd></div></dl></div>
                    </div>

                    <form method="POST" action="{{ route('user.commerce.catalog.commerce-settings', $catalog) }}" class="mt-5 flex flex-col gap-3 rounded-2xl border border-border p-4 sm:flex-row sm:items-center">@csrf<div class="flex-1"><p class="font-semibold text-title">{{ __('WhatsApp store visibility') }}</p><p class="text-sm text-body">{{ __('Enable both settings after catalog access is verified.') }}</p></div><label class="flex items-center gap-2 text-sm"><input type="hidden" name="catalog_visible" value="0"><input type="checkbox" name="catalog_visible" value="1" @checked($catalog->catalog_visible)> {{ __('Show catalog') }}</label><label class="flex items-center gap-2 text-sm"><input type="hidden" name="cart_enabled" value="0"><input type="checkbox" name="cart_enabled" value="1" @checked($catalog->cart_enabled)> {{ __('Enable cart') }}</label><x-forms.submit variant="outline" :label="__('Apply')" /></form>
                    @if($catalog->last_error)<p class="mt-4 rounded-xl bg-error/10 p-3 text-sm text-error">{{ $catalog->last_error }}</p>@endif
                </article>
            @empty
                <div class="section-card text-center text-body"><i class="ph ph-storefront text-4xl text-neutral-300"></i><h2 class="mt-2 font-semibold text-title">{{ __('No catalog connected') }}</h2><p class="text-sm">{{ __('Complete the setup form above to generate a protected feed and diagnostics.') }}</p></div>
            @endforelse
        </div>
    </div>
</x-layouts.user>
