<?php

return [
    'classic' => [
        'key' => 'classic',
        'label' => 'Classic',
        'description' => 'Classic frontend theme with calm gradients, rounded surfaces, and polished editorial spacing.',
        'preview_image' => null,
        'default_enabled' => true,
        'view_namespace' => 'frontend.themes.classic',
        'supported_section_types' => [
            'home_hero',
            'home_about',
            'home_services',
            'home_stats_number',
            'home_solutions',
            'home_marquee',
            'home_why_us',
            'home_how_work',
            'home_stack',
            'home_testimonials',
            'global_faq',
            'faq_hero',
            'home_blog',
            'blog_hero',
            'blog_featured',
            'blog_archive',
            'blog_newsletter',
            'global_contact',
            'service_category_hero',
            'service_category_services',
            'service_category_why_us',
            'service_category_process',
            'service_category_testimonials',
            'service_category_faq',
            'project_category_hero',
            'project_category_projects',
            'project_category_stack',
            'project_category_process',
            'team_hero',
            'team_members',
            'team_culture',
            'team_presence',
            'team_roles',
            'careers_hero',
            'careers_life',
            'careers_perks',
            'careers_process',
            'careers_roles',
            'about_hero',
            'about_story',
            'about_values',
            'about_team',
            'contact_page_hero',
            'contact_page_form',
            'contact_page_offices',
            'support_hero',
            'support_channels',
            'support_why',
            'support_cta',
            'marketing_hero',
            'marketing_marquee',
            'marketing_modules',
            'marketing_spotlight',
            'marketing_how_works',
            'marketing_use_cases',
            'marketing_pricing',
            'marketing_faq',
            'marketing_cta',
            'marketing_page_header',
            'marketing_compare_table',
            'marketing_modules_grid',
            'marketing_broadcasting',
            'marketing_automation',
            'marketing_why_wapro',
            'marketing_contact_info',
            'marketing_contact_form',
            'marketing_faq_categories',
            'marketing_cta_card',
            'legal_content',
        ],
        'page_layouts' => [
            'default' => [
                'label' => 'Default',
                'view' => 'layouts.page',
                'is_default' => true,
            ],
            'landing' => [
                'label' => 'Landing',
                'view' => 'layouts.landing',
            ],
            'service_category' => [
                'label' => 'Service Category',
                'view' => 'layouts.service-category',
            ],
            'project_category' => [
                'label' => 'Project Category',
                'view' => 'layouts.project-category',
            ],
        ],
        'fallback_renderer' => 'frontend.shared.sections.unsupported',
        'theme_settings_schema' => [
            'branding' => [
                'label' => 'Branding',
                'icon' => 'ph ph-shooting-star',
                'description' => 'Core brand presentation for the default Classic experience.',
                'settings' => [
                    'logo_text' => [
                        'type' => 'text',
                        'label' => 'Logo Text',
                        'default' => 'Classic',
                        'rules' => 'nullable|string|max:100',
                    ],
                    'primary_color' => [
                        'type' => 'color',
                        'label' => 'Primary Color',
                        'default' => '#2148ff',
                        'rules' => 'nullable|string|regex:/^#[0-9A-Fa-f]{6}$/',
                    ],
                    'accent_color' => [
                        'type' => 'color',
                        'label' => 'Accent Color',
                        'default' => '#15164f',
                        'rules' => 'nullable|string|regex:/^#[0-9A-Fa-f]{6}$/',
                    ],
                    'show_hero_kicker' => [
                        'type' => 'feature',
                        'label' => 'Show Hero Kicker',
                        'default' => true,
                    ],
                ],
            ],
            'navigation' => [
                'label' => 'Navigation',
                'icon' => 'ph ph-navigation-arrow',
                'description' => 'Navigation links and external URLs.',
                'settings' => [
                    'marketplace_url' => [
                        'type' => 'text',
                        'label' => 'Marketplace URL',
                        'default' => 'https://themeforest.net/user/pixelaxis',
                        'rules' => 'nullable|string|max:255',
                    ],
                ],
            ],
            'marketing' => [
                'label' => 'Marketing',
                'icon' => 'ph ph-target',
                'description' => 'Marketing/landing page content — hero CTAs, social proof, and marketing-specific copy.',
                'settings' => [
                    'show_auth_links' => [
                        'type' => 'feature',
                        'label' => 'Show Auth Links',
                        'default' => true,
                    ],
                    'sign_in_text' => [
                        'type' => 'text',
                        'label' => 'Sign In Button Text',
                        'default' => 'Sign in',
                        'rules' => 'nullable|string|max:40',
                    ],
                    'sign_up_text' => [
                        'type' => 'text',
                        'label' => 'Sign Up Button Text',
                        'default' => 'Sign up',
                        'rules' => 'nullable|string|max:40',
                    ],
                    'footer_phone' => [
                        'type' => 'text',
                        'label' => 'Footer Phone',
                        'default' => '+1 (406) 555-0120',
                        'rules' => 'nullable|string|max:40',
                    ],
                    'footer_social_facebook' => [
                        'type' => 'text',
                        'label' => 'Facebook URL',
                        'default' => '#',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_social_x' => [
                        'type' => 'text',
                        'label' => 'X (Twitter) URL',
                        'default' => '#',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_social_instagram' => [
                        'type' => 'text',
                        'label' => 'Instagram URL',
                        'default' => '#',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_social_linkedin' => [
                        'type' => 'text',
                        'label' => 'LinkedIn URL',
                        'default' => '#',
                        'rules' => 'nullable|string|max:255',
                    ],
                ],
            ],
            'footer' => [
                'label' => 'Footer',
                'icon' => 'ph ph-layout',
                'description' => 'Footer content, CTA banner, social links, and legal links.',
                'settings' => [
                    'footer_tagline' => [
                        'type' => 'textarea',
                        'label' => 'Tagline',
                        'default' => 'A senior product team for founders and operators. We design, build, and ship modern SaaS, web, and mobile products — from discovery to launch.',
                        'rules' => 'nullable|string|max:400',
                    ],
                    'footer_email' => [
                        'type' => 'text',
                        'label' => 'Email',
                        'default' => 'hello@example.com',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_address' => [
                        'type' => 'text',
                        'label' => 'Address',
                        'default' => 'Remote-first · HQ in San Francisco · CA, United States',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_newsletter_heading' => [
                        'type' => 'text',
                        'label' => 'Newsletter Heading',
                        'default' => 'Field notes from real product builds',
                        'rules' => 'nullable|string|max:100',
                    ],
                    'footer_newsletter_subheading' => [
                        'type' => 'text',
                        'label' => 'Newsletter Subheading',
                        'default' => 'Stay in the loop',
                        'rules' => 'nullable|string|max:80',
                    ],
                    'footer_newsletter_disclaimer' => [
                        'type' => 'text',
                        'label' => 'Newsletter Disclaimer',
                        'default' => 'Engineering write-ups, post-mortems, and the occasional launch. No spam.',
                        'rules' => 'nullable|string|max:200',
                    ],
                    'footer_social_linkedin' => [
                        'type' => 'text',
                        'label' => 'LinkedIn URL',
                        'default' => '',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_social_twitter' => [
                        'type' => 'text',
                        'label' => 'Twitter / X URL',
                        'default' => '',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_social_github' => [
                        'type' => 'text',
                        'label' => 'GitHub URL',
                        'default' => '',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_social_dribbble' => [
                        'type' => 'text',
                        'label' => 'Dribbble URL',
                        'default' => '',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_cta_badge' => [
                        'type' => 'text',
                        'label' => 'CTA Badge Text',
                        'default' => 'Now booking · Q3 builds',
                        'rules' => 'nullable|string|max:80',
                    ],
                    'footer_cta_heading' => [
                        'type' => 'text',
                        'label' => 'CTA Heading',
                        'default' => 'Have an idea worth shipping? Let\'s scope it together.',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_cta_subheading' => [
                        'type' => 'text',
                        'label' => 'CTA Subheading',
                        'default' => 'Free 30-minute scope call with the team that would actually build it. Reply within 48 hours.',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_cta_primary_text' => [
                        'type' => 'text',
                        'label' => 'CTA Primary Button Text',
                        'default' => 'Start a project',
                        'rules' => 'nullable|string|max:80',
                    ],
                    'footer_cta_primary_link' => [
                        'type' => 'text',
                        'label' => 'CTA Primary Button Link',
                        'default' => '/contact',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_cta_ghost_text' => [
                        'type' => 'text',
                        'label' => 'CTA Ghost Button Text',
                        'default' => 'Or talk to sales',
                        'rules' => 'nullable|string|max:80',
                    ],
                    'footer_cta_ghost_link' => [
                        'type' => 'text',
                        'label' => 'CTA Ghost Button Link',
                        'default' => '#contact',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_feedback_heading' => [
                        'type' => 'text',
                        'label' => 'Feedback Banner Heading',
                        'default' => 'We Value Your Feedback',
                        'rules' => 'nullable|string|max:100',
                    ],
                    'footer_feedback_subheading' => [
                        'type' => 'text',
                        'label' => 'Feedback Banner Subheading',
                        'default' => 'Share your thoughts with us to help improve your experience!',
                        'rules' => 'nullable|string|max:200',
                    ],
                    'footer_feedback_link' => [
                        'type' => 'text',
                        'label' => 'Feedback Link',
                        'default' => '#feedback',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_copyright' => [
                        'type' => 'text',
                        'label' => 'Copyright Text',
                        'default' => 'Classic theme. Crafted with care.',
                        'rules' => 'nullable|string|max:200',
                    ],
                    'footer_link_terms' => [
                        'type' => 'text',
                        'label' => 'Terms of Use URL',
                        'default' => '#',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_link_privacy' => [
                        'type' => 'text',
                        'label' => 'Privacy Policy URL',
                        'default' => '#',
                        'rules' => 'nullable|string|max:255',
                    ],
                    'footer_link_cookies' => [
                        'type' => 'text',
                        'label' => 'Cookie Policy URL',
                        'default' => '#',
                        'rules' => 'nullable|string|max:255',
                    ],
                ],
            ],
        ],
    ],
];
