name: Cpanel Deployment

on:
  push:
    branches: [main]

jobs:
  cpanel-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: npm install
        run: npm install --force

      - name: npm run bundle
        run: npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.safiul.pxlaxis.com
          username: yacht@safiul.pxlaxis.com
          password: "4pGUexL!DXq5kdgX"
          server-dir: whatsapp.safiul.pxlaxis.com/
          exclude: |
            **/.git*
            **/.git*/**
            **/storage/**
            **/public/storage/**
            **/node_modules/**
